model:
    hidden_channels: 192
    hidden_channels_ffn_text_encoder: 768
    num_heads_text_encoder: 2
    num_layers_text_encoder: 6
    kernel_size_text_encoder: 3
    dropout_p_text_encoder: 0.1
    spec_channels: 80
    kernel_size_posterior_encoder: 5
    dilation_rate_posterior_encoder: 1
    num_layers_posterior_encoder: 16
    n_heads: 2
    n_layers: 6
    kernel_size: 3
    p_dropout: 0.1
    n_speakers: 2
    n_languages: 2
    embedded_speaker_dim: 256
    embedded_language_dim: 4
    prosody_emb_dim: 256
    kernel_size_flow: 5
    dilation_rate_flow: 1
    num_layers_flow: 4
    resblock_type_decoder: '1'
    resblock_dilation_sizes_decoder:
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
    resblock_kernel_sizes_decoder:
        - 3
        - 7
        - 11
    upsample_kernel_sizes_decoder:
        - 16
        - 16
        - 4
        - 4
    upsample_initial_channel_decoder: 512
    upsample_rates_decoder:
        - 8
        - 8
        - 2
        - 2
    segment_size: 32

# Additional global parameters (if needed)
n_vocab: 1000
