train:
    log_interval: 100
    eval_interval: 200
    # log_interval: 5
    # eval_interval: 10
    seed: 1234
    epochs: 10000
    learning_rate: 0.0001
    betas:
        - 0.8
        - 0.99
    eps: 1e-9
    batch_size: 32
    fp16_run: false
    bf16_run: false
    lr_decay: 0.999875
    segment_size: 8192
    init_lr_ratio: 1
    warmup_epochs: 0
    c_mel: 45
    c_kl: 1.0
    c_prosody_kl: 0.001
    use_sr: true
    max_speclen: 512
    port: "8001"
    keep_ckpts: 3
    num_workers: 12
    log_version: 0
    ckpt_name_by_step: false
    accumulate_grad_batches: 1

model:
    hidden_channels: 192
    hidden_channels_ffn_text_encoder: 768
    num_heads_text_encoder: 2
    num_layers_text_encoder: 6
    kernel_size_text_encoder: 3
    dropout_p_text_encoder: 0.1
    spec_channels: 513
    kernel_size_posterior_encoder: 5
    dilation_rate_posterior_encoder: 1
    num_layers_posterior_encoder: 16
    n_heads: 2
    n_layers: 6
    kernel_size: 3
    p_dropout: 0.1
    n_speakers: 2
    n_languages: 2
    embedded_speaker_dim: 256
    embedded_language_dim: 4
    prosody_emb_dim: 256
    kernel_size_flow: 5
    dilation_rate_flow: 1
    num_layers_flow: 4
    resblock_type_decoder: '1'
    resblock_dilation_sizes_decoder:
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
        - - 1
          - 3
          - 5
    resblock_kernel_sizes_decoder:
        - 3
        - 7
        - 11
    upsample_kernel_sizes_decoder:
        - 16
        - 16
        - 4
        - 4
    upsample_initial_channel_decoder: 512
    upsample_rates_decoder:
        - 8
        - 8
        - 2
        - 2

data:
    max_wav_value: 32768.0
    sampling_rate: 22050
    filter_length: 1024
    hop_length: 256
    win_length: 1024
    n_mel_channels: 80
    mel_fmin: 0.0
    mel_fmax: 8000.0
    n_fft: 1024
    use_spectral_norm: false
    speaker_dict_path: "data/speaker_dict_ljspeech.json"
    language_dict_path: "data/language_dict_ljspeech.json"

# Additional global parameters (if needed)
n_vocab: 1000
